# Uncomment for use in a non-containerised environment
# When used in a container, environment variables should
# control the database settings
#database:
#  name: "paxton"
#  address: "localhost"
#  port: "3306"

post-templates:
  - id: "example"
    messages:
      - title: "Example #{Placeholder.1}: {Placeholder.2}" # optional
        description: "" # optional
        url: "https://example.com" # optional
        timestamp: 1702217350727 # optional EPOCH SECONDS
        color: 0xA1B2C3 # optional
        thumbnail: "https://example.com/image.jpg" # optional
        author: # optional
          name: "Johnny Appleseed" # optional
          icon-url: "https://example.com/image.jpg" # optional
          url: "https://example.com" # optional
        footer: # optional
          text: "Footer Text"
          icon-url: "https://example.com/image.jpg" # optional
        img: "https://example.com/image.jpg" # optional
        fields: # optional
          - name: "Name" # required
            value: "Value" # required
            inline: true # optional
            checked: false # optional